name: Sphix documentation

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  schedule:
    - cron:  '15 1 * * *'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
       name: Install debian packages
       run: sudo apt-get install python3-pip make
      -
        name: Install dependencies
        run: |
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install -r doc/requirements.txt
      -
        name: Generate sphix docs
        run: cd doc && make html
