name: Python type check

on:
  push:
    branches: [ master ]
    tags: [ "*" ]
  schedule:
    - cron:  '15 1 * * *'

jobs:
  mypy:
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:default
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install MonetDBe in developer mode
        run: MONETDB_BRANCH=default python3 -m pip install -e .[test]
      -
        name: Run mypy static code checks
        run: mypy monetdbe tests
