name: Code syle check

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  schedule:
    - cron:  '15 1 * * *'

jobs:
  linux-pycodestyle:
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:default
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install MonetDBe in developer mode
        run: MONETDB_BRANCH=default python3 -m pip install -e .[test]
      -
        name: Check the python coding style
        run: pycodestyle monetdbe tests
