name: Code syle check

on:
  push:
    branches: [ master ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  linux-pycodestyle:
    runs-on: ubuntu-20.04
    container: monetdb/dev-builds:Jan2022
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install MonetDBe in developer mode
        run: MONETDB_BRANCH=Jul2021 python3 -m pip install -e .[test]
      -
        name: Check the python coding style
        run: pycodestyle monetdbe tests
